version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5400:5432"
    volumes:
      - /Users/jkrishna:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=postgres'

  